apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-nodejs
    app.kubernetes.io/part-of: devfile-sample-nodejs
  name: devfile-sample-nodejs
  namespace: user1-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-nodejs
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-nodejs
    spec:
      containers:
      - image: quay.io/jduimovich0/devfile-sample-nodejs@sha256:1cf2362b1912b40f2eec555180e91696ba30acb6fcaa42ffc5981ed6b4856497
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
